### ISSUE TITLE
run code issue

### ISSUE THREAD

**Issue by jackxinzheshida** [cyyever/distributed_learning_simulator#8]
![Image](https://github.com/user-attachments/assets/18fdf540-ff9e-4a03-a8b6-59ef46adb14a)
can not find the global_config in config

![Image](https://github.com/user-attachments/assets/b7e5c70b-ad50-497d-a64b-1755f680f6fc)
can not find this function too
I am a new student in this area ,I will be very happy to receive reply,thank you

**Comment by cyyever** [comment]
Hi, in what file did you have this issue? Since I just fixed some issues, you'd better update the latest code, run ``python3 -m pip install . --upgrade --force-reinstall --user``, and then run ``bash test.sh`` to ensure that the code works.

**Comment by jackxinzheshida** [comment]
> Hi, in what file did you have this issue? Since I just fixed some issues, you'd better update the latest code, run `python3 -m pip install . --upgrade --force-reinstall --user`, and then run `bash test.sh` to ensure that the code works.

I am very glad to see your apply.First,i execute pip install . --upgrade --force-reinstall --user.Then i can find some dependencies was install in pip list.But,When i was execute the first code in test.sh,the terminal gave me some execute probelms like the picture.



![Image](https://github.com/user-attachments/assets/eee8d1da-ddfd-40bf-aecd-86966b486dae)

![Image](https://github.com/user-attachments/assets/df32c99d-a1ce-406c-80ab-917036d42464)

![Image](https://github.com/user-attachments/assets/35d7c029-59a0-484a-b20e-0a55a4190826)
Through the problems ,i find that there are some problems in the code like the pictures

![Image](https://github.com/user-attachments/assets/971c21b5-8d5f-420e-b6fd-f91c8f44e8f5)

![Image](https://github.com/user-attachments/assets/2cff655f-2181-4cd3-b635-c09b1f25e169)

**Comment by cyyever** [comment]
What is your 'nvidia-smi' output? The code couldn't find a device for training. Do you have proper CUDA setup?

**Comment by cyyever** [comment]
Please git pull the code and reinstall the dependencies via ``python3 -m pip install . --upgrade --force-reinstall --user``. I have relaxed the device filter.

**Comment by jackxinzheshida** [comment]
> Please git pull the code and reinstall the dependencies via `python3 -m pip install . --upgrade --force-reinstall --user`. I have relaxed the device filter.

I try again and run the test.sh but there are some problems.

![Image](https://github.com/user-attachments/assets/d3b93c24-2c0e-4b25-8be5-b8b6d6bc33fc)

**Comment by cyyever** [comment]
I fixed another dependency error, please re-run ``python3 -m pip install . --upgrade --force-reinstall --user`` .  Now you should be able to download imdm from HuggingFace

**Comment by jackxinzheshida** [comment]
> I fixed another dependency error, please re-run `python3 -m pip install . --upgrade --force-reinstall --user` . Now you should be able to download imdm from HuggingFace

Thanks again for you reply.After running the multi-process pool, the program does not respond and no error is reported.

![Image](https://github.com/user-attachments/assets/3d4d0c2d-8fe4-4028-8d64-cd4ae4256e6f)
And in the Minist document,i find maybe loss some documents.

![Image](https://github.com/user-attachments/assets/4cbf2677-2021-440f-a257-4e6424e1e827)

**Comment by cyyever** [comment]
OK, let me test the code in a clean Docker enviroment to find some interesting bug.

**Comment by jackxinzheshida** [comment]
Waiting for your good news

**Comment by cyyever** [comment]
Sorry, I have fixed another bug introduced by recent code refactoring. It's related to dataset preprocessing. Because I have local dataset cache, the bug has not been discovered until I run it in Docker.   
Please re-run ``python3 -m pip install . --upgrade --force-reinstall --user`` as before. MNIST training should work.

**Comment by jackxinzheshida** [comment]
> Sorry, I have fixed another bug introduced by recent code refactoring. It's related to dataset preprocessing. Because I have local dataset cache, the bug has not been discovered until I run it in Docker. Please re-run `python3 -m pip install . --upgrade --force-reinstall --user` as before. MNIST training should work.

I am sorry to say that the problem still exit.

![Image](https://github.com/user-attachments/assets/3a1e9452-1641-4bcd-8a42-8c9426c37fcf)

First,I want to say that i use the anaconda to run this project in my Laptop,Every time i run python3 -m pip install . --upgrade --force-reinstall --target=/home/jackxin/anaconda3/envs/gtgtest2/lib/python3.12/site-packages to install the dependcies.Because if you directly execute your statement, the corresponding dependencies will be installed into the global pip, rather than the conda pip packages.I don't know if this is the cause of the problem. I only have one GPU. Is the code set to run on multiple GPUs, or is something else preventing the code from executing?

**Comment by jackxinzheshida** [comment]
> Sorry, I have fixed another bug introduced by recent code refactoring. It's related to dataset preprocessing. Because I have local dataset cache, the bug has not been discovered until I run it in Docker. Please re-run `python3 -m pip install . --upgrade --force-reinstall --user` as before. MNIST training should work.

And I find this problem always exit.

![Image](https://github.com/user-attachments/assets/a521bea5-3b5a-4018-b01d-798eebaae3c0)

![Image](https://github.com/user-attachments/assets/b475540b-d6ad-448d-8782-ef281d15063a)
The matplotlib and seaborn i can install but another problem is caused by the dependcies.

**Comment by jackxinzheshida** [comment]
> Sorry, I have fixed another bug introduced by recent code refactoring. It's related to dataset preprocessing. Because I have local dataset cache, the bug has not been discovered until I run it in Docker. Please re-run `python3 -m pip install . --upgrade --force-reinstall --user` as before. MNIST training should work.

the fedavg log 

![Image](https://github.com/user-attachments/assets/930e75b0-b5f8-4ac5-9080-64bad2efc1d4)
the gtgshapley log

![Image](https://github.com/user-attachments/assets/3ccb24bf-9b27-4d1d-ad68-8c289993fe2b)

**Comment by cyyever** [comment]
@jackxinzheshida Yes, because of that error, you need to reinstall dependencies

**Comment by jackxinzheshida** [comment]
> [@jackxinzheshida](https://github.com/jackxinzheshida) Yes, because of that error, you need to reinstall dependencies

Now I run test.sh,I find that the minist can run.But when I run the second experiment,there are some errors in the terminal.

![Image](https://github.com/user-attachments/assets/3bf2b62a-3608-4d20-bb49-9cbeaba45774)

**Comment by cyyever** [comment]
Fixed.

**Comment by jackxinzheshida** [comment]
> Fixed.

![Image](https://github.com/user-attachments/assets/6f999a2e-6669-40d7-962b-e4f8d0969c93)
I apologize for the delayed response as I was occupied with other matters recently. Now I'm encountering a new issue when running the test.sh script.

**Comment by jackxinzheshida** [comment]
> Fixed.

Now，I can run the test.sh which use the minist and cifar10.But the second code: python3 ./simulator.py --config-name fed_avg/imdb.yaml ++fed_avg.round=1 ++fed_avg.epoch=1 ++fed_avg.worker_number=2 ++fed_avg.debug=True
run failed 

![Image](https://github.com/user-attachments/assets/1d0cdc59-13c3-4512-941f-e21408af5c3c)

**Comment by cyyever** [comment]
I can‘t reproduce. IMDB is downloaded from Hugging Face Hub. Make sure that you can access it. Also make sure that you use latest code from Github. 
```
git pull
python3 -m pip install . --upgrade --force-reinstall --user
```
